from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class StreamProtocol(Protocol):
    """Streaming output abstraction."""

    def start(self) -> None: ...
    def feed(self, token: str) -> None: ...
    def finish(self) -> str: ...


@runtime_checkable
class UIProtocol(Protocol):
    """UI abstraction consumed by the agent loop."""

    def print_assistant(self, text: str) -> None: ...
    def print_tool_call(self, name: str, input_data: Any) -> None: ...
    def print_tool_result(self, name: str, output: Any) -> None: ...
    def print_error(self, msg: str) -> None: ...
    def print_status(self, msg: str) -> None: ...
    def get_stream_printer(self) -> StreamProtocol: ...
